GTEx Documentation
ElucidataInc/polly-docs pull request #123
Opened 2020-08-29 08:08 UTC by Ayush-Praveen

2020-08-29 16:10 UTC, avijitzutshi commented on docs/Data Lake.md
> +Using GTEx card on the Discover portal GTEx tissues can be accessed.
rephrase and remove portal. Just mention it as Discover.

2020-08-29 16:11 UTC, avijitzutshi commented on docs/Data Lake.md
> +The tab provides a metadata table to check different characterstics of samples. Further various parameters of PCA can be adjusted.
"Further ... " to "Furthermore ... "

2020-08-29 16:12 UTC, avijitzutshi commented on docs/Data Lake.md
> +A Single gene can be selected to plot violin for it's expression across different tissues.
lower case "S"

2020-08-29 16:13 UTC, avijitzutshi requested changes
added comments

2020-08-30 09:55 UTC, Ayush-Praveen commented
Hello @avijitzutshi , I have addressed your comments, can you have a look. Thanks

2020-08-30 16:09 UTC, avijitzutshi approved these changes

2020-08-30 16:10 UTC, merged